config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'stores#index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  # root "articles#index"
  resources :stores
  resources :articles, only: [:show]

  resources :orders do
    member do
      get :checkout
      get :confirmation
    end
  end
  post 'orders/add'
  post 'orders/remove'
  resources :articles do
    resources :article_orders, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :store
  has_many :article_orders
  has_many :orders, through: :article_orders

  validates :title, presence: true
  validates :description, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :weight, presence: true
end

app/models/article_order.rb
class ArticleOrder < ApplicationRecord
  belongs_to :order
  belongs_to :article

  validates :quantity, presence: true

  def total
    article.price * quantity
  end
end

app/models/confirmed_order.rb
class ConfirmedOrder < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :article_orders
  has_many :articles, through: :article_orders

  validates :number, presence: true
  validates :number, uniqueness: true
  validates :delivery_time, presence: true

  def total
    article_orders.to_a.sum { |article_order| article_order.total }
  end
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :articles, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :image_url, presence: true
  validates :rating, presence: true
  validates :estimated_delivery_time, presence: true
  validates :delivery_fees, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_many :articles, through: :orders

  geocoded_by :delivery_address
  after_validation :geocode, if: :will_save_change_to_delivery_address?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_render_order
  before_action :initialize_order

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end

  def set_render_order
    @render_order = true
  end

  def initialize_order
    @order ||= Order.find_by(id: session[:order_id], user_id: current_user.id) if current_user

    return unless @order.nil?

    @order = Order.new(number: SecureRandom.hex(4), delivery_time: 'time', confirmed: false)
    @order.user = current_user
    @order.save
    session[:order_id] = @order.id
  end
end

app/controllers/article_orders_controller.rb
class ArticleOrdersController < ApplicationController
  def create
    # Find associated article and current order
    chosen_article = Article.find(params[:article_id])
    current_order = @current_order

    # If order already has this article then find the relevant article_order and iterate quantity otherwise create a new article_order for this article
    if current_order.articles.include?(chosen_article)
      # Find the article_order with the chosen_article
      @article_order = current_order.article_orders.find_by(article_id: chosen_article)
      # Iterate the article_order's quantity by one
      @article_order.quantity += 1
    else
      @article_order = ArticleOrder.new
      @article_order.order = current_order
      @article_order.article = chosen_article
    end

    # Save and redirect to order show path
    @article_order.save
    redirect_to order_path(current_order)
  end

  def destroy
    @article_order = ArticleOrder.find(params[:id])
    @article_order.destroy
    redirect_to order_path(@current_order)
  end

  def add_quantity
    @article_order = ArticleOrder.find(params[:id])
    @article_order.quantity += 1
    @article_order.save
    redirect_to order_path(@current_order)
  end

  def reduce_quantity
    @article_order = ArticleOrder.find(params[:id])
    @article_order.quantity -= 1 if @article_order.quantity > 1
    @article_order.save
    redirect_to order_path(@current_order)
  end

  private

  def article_order_params
    params.require(:article_order).permit(:quantity, :article_id, :order_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
    @order = Order.find_by(user_id: current_user.id)
    @article_order = @order&.article_orders&.find_by(article_id: @article.id)
  end
end

app/controllers/confirmed_orders_controller.rb
class ConfirmedOrdersController < ApplicationController
  def index
    @confirmed_orders = ConfirmedOrder.all
  end

  def show
    @confirmed_order = ConfirmedOrder.find(params[:id])
  end

  def new
    @confirmed_order = ConfirmedOrder.new
  end

  def create
    @confirmed_order = ConfirmedOrder.new(confirmed_order_params)
    @current_order.article_orders.each do |article|
      @order.article_orders << article
      article.order_id = nil
    end
    @confirmed_order.save
    Order.destroy(session[:order_id])
    session[:order_id] = nil
    redirect_to root_path
  end

  private

  def order_params
    params.require(:confirmed_order).permit(:name, :email, :address, :pay_method)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_cart_to_confirmed, only: :confirmation

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def add
    @article = Article.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_article_item = @order.article_orders.find_by(article_id: @article.id)
    if current_article_item && quantity.positive?
      current_article_item.update(quantity:)
    elsif quantity <= 0
      current_article_item.destroy
    else
      @order.article_orders.create(article: @article, quantity:)
    end

    respond_to do |format|
      if @order.save
        format.html { redirect_to order_path(@order) }
        # format.json # Follow the classic Rails flow and look for a create.json view
      else
        format.html { render 'orders/show', status: :unprocessable_entity }
        # format.json # Follow the classic Rails flow and look for a create.json view
      end
    end
  end

  def remove
    ArticleOrder.find_by(id: params[:id]).destroy
  end

  def checkout; end

  def confirmation
    @marker_user =
      {
        lat: current_user.latitude,
        lng: current_user.longitude,
        info_window_html: render_to_string(partial:
        'info_window', locals: { user: current_user }),
        marker_html: render_to_string(partial: 'marker_user', locals: { user: current_user })
      }

    @marker_order =
      {
        lat: @order.latitude,
        lng: @order.longitude,
        info_window_html: render_to_string(partial:
        'info_window', locals: { order: @order }),
        marker_html: render_to_string(partial: 'marker_order', locals: { order: @order })
      }
  end

  private

  def set_cart_to_confirmed
    @order.confirmed = true
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home; end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: :show

  def index
    @render_order = false
    @stores = Store.all
    return unless params[:query].present?

    sql_subquery = <<~SQL
      stores.title ILIKE :query
      OR articles.title ILIKE :query
    SQL
    # j'aimerais avoir le résultat des pharmacies qui correspond a un article que je recherche.
    @stores = @stores.joins(:articles).where(sql_subquery, query: "%#{params[:query]}%").distinct
  end

  def show
    @articles = @store.articles
  end

  private

  def set_store
    @store = Store.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/article_orders/index.html.erb
<h1>Cart orders  </h1>

<div class="button_history">
    <%= link_to "Show my commands history", user_orders_path(current_user) %>
</div>

app/views/articles/_article_items.html.erb
<% @order.article_orders.each do |article_order| %>
    <% article = article_order.article %>
    <div id= ""> <%= "cart-#{article.id}" %>
        <div class="d-flex justify-content-between align-items-start mb-4">
            <div>
            <h3 class="fs-4 title text-dark"><%= article.title %></h3>
            <div class="main pb-2"><%= sprintf('%.2f', article.price.to_f) %> CHF</div>
            <span class="text-secondary"><%= article.description.truncate(24)%></span>
            </div>
            <div >
            <%= image_tag(article.image_url, width: "120", height: "120" ) %>
            </div>

            <%= form_with(url: orders_add_path) do |f|%>
                <%= f.hidden_field :id, value: article.id %>
                <%= f.number_field :quantity, value: article_order.quantity, min: 0 %>
                <%= f.submit "Add to cart", class: "btn_magic fs-3 d-flex justify-content-center " %>
            <% end %>

            <%= form_with(url: orders_remove_path) do |f|%>
                <%= f.hidden_field :id, value: article_order.id %>
                <%= f.submit "X" %>
            <% end %>
            <strong>Total : </strong>
                <%= article_order.total %>
        </div>
    </div>

<% end %>

app/views/articles/index.hmtl.erb
<h2>All articles</h2>

<% @articles.each do |article| %>
  <p>Name: <%= article.name %>; unit price of <%= number_to_currency(article.price) %></p>
  <p>
    <%= link_to "Edit", edit_article_path(article) %> |
    <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"} %>
    <%= button_to "Add #{article.name} to cart", article_orders_path(:article_id => article.id) %>
  </p>
<% end%>
<!-- New? Voir si enlever -->
<%= link_to "New article", new_article_path %>

<%= button_to "Add #{article.name} to cart", article_orders_path(:article_id => article.id)%>

app/views/articles/show.html.erb
<div class="container">
  <div class="d-flex">
    <%=link_to "Home", stores_path, class:"text-primary p-1 text-decoration-none" %>
    <p class="p-1">></p>
    <p class="text-primary p-1">
      <%= link_to store_path(@article.store), style: "text-decoration: none" do %>
        <%= @article.store.title %>
        <% end %>
    </p>
    <p class="p-1">></p>
    <p class="text-primary p-1"><%= @article.title %></p>
  </div>
  <div class="image_article" style="background-image: url(<%= image_path(@article.image_url) %>)">
    <div class="d-flex justify-content-between">
      <div>
        <%= link_to store_path(@article.store), style: "text-decoration: none" do %>
            <%= image_tag("back.png", width: "45", height: "45", class:"rounded-circle mt-1") %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="titles_article">
    <h1 class="title_article fw-bolder"><%= @article.title %></h1>
  </div>

  <div class="price_article"><strong>Price: </strong>
    <span class="main"><%= sprintf('%.2f', @article.price.to_f) %> CHF </span>
    <p class="category_article"><strong>Category: </strong><%= @article.category %></p>
  </div>

  <div id="description_article">
    <strong><h4 id="description_article">Description</h4></strong>
    <p id="description_article"><%= @article.description %></p>
  </div>

<%= form_with(url: orders_add_path) do |f| %>
  <%= f.hidden_field :id, value: @article.id %>
  <div class="buttons_articles">
    <p class="quantity_articles">Quantity:</p>
    <div class="m-2"><%= f.select :quantity, 1..5, {}, class: "articles_select select-button" %></div>
    <%= f.submit "Add to cart", id: "add-to-cart-btn", class: "articles_button btn_magic fs-3 d-flex justify-content-center text-white" %>
  </div>
<% end %>

<!-- La jauge de poid -->
  <div class="jauge_articles d-flex justify-content-center">
    <%= render "shared/jauge", article: @article %>
  </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    $('#add-to-cart-btn').click(function(e) {
      e.preventDefault(); // Prevent the default form submission

      // Show the popup message
      alert('Item added to cart');

      // Submit the form
      $(this).closest('form').submit();
    });
  });
</script>

app/views/orders/_article_items.html.erb
<div class="container" data-controller="insert-in-cart">
  <div>
    <% i = 0 %>
    <% @order.article_orders.each do |article_order| %>
      <% article = article_order.article %>
      <div class="d-flex mb-4 flex-column" data-insert-in-cart-target="items">
        <div>
          <div class="item-container">
            <%= image_tag(article.image_url, width: "120", height: "120") %>
            <h3 class="d-flex align-items-end flex-column fs-4 title text-dark">
              <%= article.title %>
              <div class="item_price pb-2 text-black">Item's Price:
                <span id="price<%= i %>"><%= sprintf('%.2f', article.price.to_f) %> CHF
                </span>
              </div>
            </h3>
          </div>

        </div>
        <%= form_with url: orders_add_path, data: {action: "submit->insert-in-cart#send", insert_in_cart_target: "form", insert_in_cart_id_param: i, insert_in_cart_num_param: article_order.quantity } do |f|  %>
          <%= f.hidden_field :id, value: article.id %>
          <div class="bottom">
            <div class="buttons">
              <%= f.number_field :quantity, value: article_order.quantity, min: 0, data: {action: "input->insert-in-cart#retrieveQuantity"}, class: "input-quantity" %>
              <%= f.submit "Add", class: "add-btn fs-3 d-flex justify-content-center"  %>
            <% end %>
            <%= form_with(url: orders_remove_path) do |f|%>
              <%= f.hidden_field :id, value: article_order.id %>
              <%= f.submit "X", class: "delete btn-success fs-3 d-flex justify-content-center " %>
            <% end %>
            </div>
            <div class="d-flex align-items-end flex-column main">

              <p class="totale">Total: <span data-insert-in-cart-target="total"><%= sprintf('%.2f',article_order.total.to_f) %> CHF</span></p>
            </div>
          </div>
        </div>
        <% i += 1 %>
      <% end %>
      <div class="d-flex justify-content-between pt-2">
        <div>
          <h5>Cart total: </h5>
        </div>
        <div class="d-flex justify-content-end main">
          <h5 data-insert-in-cart-target="endtotal"><%= sprintf('%.2f', @order.total.to_f) %> CHF</h5></h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/orders/_info_window.html.erb
<h2>Me</h2>
<p><%= current_user.delivery_address%></p>

app/views/orders/_order.html.erb
<h1 class="h1">My cart</h1>
<% if @order.article_orders.count > 0 %>
    <%= render 'article_items' %>
    <%= link_to "Order", checkout_order_path(@order), class: "btn_magic fs-3 d-flex justify-content-center text-white", style: "text-decoration: none;" %>
    <%= link_to "Add other articles", store_path(@order.article_orders.first.article.store.id), class: "order btn_add fs-3 d-flex justify-content-center text-black", style: "text-decoration: none;" %>
<% else %>
    <%= link_to "Add Articles", stores_path, class: "other_article btn_add fs-3 d-flex justify-content-center text-black", style: "text-decoration: none;" %>
<% end %>

app/views/orders/checkout.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">

    <!-- bouton back -->
    <% if @order.id == nil %>
      <%= link_to stores_path, style: "text-decoration: none" do %>
        <%= image_tag("back.png", width: "45", height: "45", class:"rounded-circle my-3") %>
      <% end %>
    <% else %>
      <%= link_to order_path(@order), style: "text-decoration: none" do %>
        <%= image_tag("back.png", width: "45", height: "45", class:"rounded-circle my-3") %>
      <% end %>
    <% end %>

    <!-- adrress de livraison -->

    <h1 class="mb-4">Delivery Address</h1>

    <div class="card_address d-flex justify-content-between">
      <%= image_tag("marker_payement.png", width: "40", height: "30", class:"") %>
      <p class="d-flex justify-content-center">Rte de Praz Véguey 29, 1022 Chavannes-près-Renens</p>
    </div>

    <div class="line"></div>

    <h1 class="mb-5">Payment</h1>

    <% order_total = @order.article_orders.sum(&:total) %>
    <% fee = @order.article_orders.first.article.store.delivery_fees %>
    <% total = order_total + fee %>
    <div class="d-flex justify-content-between">
      <div>
        <p class="fs-5">Cart total :</p>
        <p class="fs-5">Delivery fees :</p>
        <p class="fs-5 fw-bold">Total price :</p>
      </div>
      <div>
        <p class="d-flex justify-content-end fs-5 main"> <%= sprintf('%.2f', order_total.to_f) %> CHF</p>
        <p class="d-flex justify-content-end fs-6 pb-1"> <%= sprintf('%.2f', fee.to_f) %> CHF</p>
        <p class="d-flex justify-content-end fs-5 fw-bold main"> <%= sprintf('%.2f', total.to_f) %> CHF</p>
      </div>
    </div>

    <div class="line"></div>

    <%= render 'credit_card' %>

    </div>

    <%= link_to "Validate", confirmation_order_path, class:"btn btn_magic fs-3 d-flex justify-content-center text-white" %>


  </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">

    <div class="image_p" style="background-image: url('Mettre image article')">
    <div class="d-flex justify-content-between">
        <div class="border border-white rounded-circle fs-6">
          <%=link_to "Back", stores_path %>
        </div>
    </div>
  </div>
  <div>
    <h1 class="my-3 fw-bolder fs-1">Orders list </h1>
  </div>

  <% @orders.each do |order| %>
    <div class="justify-content-between ">
      <p>Order number: </p>
      <p><%= link_to "#{order.number}", order_path(@order) %></p>
      <p>Order date: </p>
      <p><%= order.updated_at %></p>
    </div>
  <% end %>


</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm sticky-sm-bottom">
  <div class="container-fluid">
    <div class="all d-flex align-items-center">

    <%= link_to stores_path, class: "home" do %>
      <span class="navbar-home-icon"><i class="home fas fa-home"></i></span>
    <% end %>

    <% if @order.confirmed %>
      <%= link_to confirmation_order_path, class: "helice" do %>
        <span class="navbar-helice-icon">
        <%= image_tag("helice.png", class: "helice") %>
        </span>
      <% end %>
    <% else %>
      <button class= "helice, disabled"> </button>
    <% end %>

    <% if @order.id.nil?  %>
      <button class= "navbar-cart-icon, disabled"> </button>
    <% else %>
      <%= link_to order_path(@order), class: "cart" do %>
      <span class="navbar-cart-icon"><i class="cart fas fa-shopping-cart"></i>
      <% end %>
    <% end %>

    </div>
  </div>
</nav>

app/views/stores/index.html.erb
<!-- debug button logout-->

<div class="container">

  <!-- Search bar intelligente-->

  <div class="row justify-content-center">
    <div class="col-sm-8 my-3 p-2 bd-highlight">
      <%= image_tag("loupe2.png", :crop=>"fill", width: "28", height: "28", class:"ms-2 mt-1 position-absolute") %>
      <%= form_with url: stores_path, method: :get, class: "" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "py-2 form-control rounded-pill main_grey position-arelative ps-5",
              placeholder: "Pharmacys, Articles, etc..."
          %>
          <div id="search_result" style="color: grey">
            <% if params[:query] %>
              <p> You found <%=  @stores.count  %> stores </p>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>

    <!-- resultat de la search_bar -->

  <% @stores.each do |store| %>
    <div class="card">
      <%= link_to  store_path(store) do%>
        <%= image_tag(store.image_url, class: "image") %>
      <%end%>
      <div class="d-flex justify-content-between ">
        <h4 class="title mt-1 ="><%= store.title %></h4>
        <span class="d-flex align-middle">
          <div class="fs-5 align-top">
            <%= image_tag("etoile.jpg", width: "16", height: "16") %>
            <span class="fs-6"><%= sprintf('%.2f', store.rating) %> (<%= rand(60..120)%> notes)</span>
          </div>
        </span>
      </div>
      <div class="d-flex justify-content-between">
        <p>Delivery fees: <%= sprintf('%.2f', store.delivery_fees) %> CHF</p>
        <p class="input-estimated_delivery_time" name="estimated_delivery_time" readonly>~<%= store.estimated_delivery_time %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/stores/show.html.erb
<!-- Store -->

<div class="container">
  <div class="row">
    <div class="d-flex" id="store">
      <%=link_to "Home", stores_path, class:"text-primary p-1 text-decoration-none" %>
      <p class="p-1">></p>
      <p class="text-primary p-1"><%= @store.title %></p>
    </div>

    <!-- image + bouton back et search -->
    <div class="image_p" style="background-image: url(<%= image_path(@store.image_url) %>)">
      <div class="d-flex justify-content-between">
        <div>
          <%= link_to stores_path, style: "text-decoration: none" do %>
            <%= image_tag("back.png", width: "45", height: "45", class:"rounded-circle mt-3") %>
          <% end %>
        </div>


        <!-- image de la loupe non active -->
        <%# <div>
          <%= image_tag("loupe.png", width: "45", height: "45", class:"rounded-circle mt-3") %>
        <%# </div> %>
      </div>
    </div>

    <div>
      <h1 class="my-3 fw-bolder fs-1">
        <%= @store.title %>
      </h1>
      <span class="d-flex">
        <div class="fs-5">
          <%= image_tag("etoile.jpg", width: "16", height: "16") %>
          <%= sprintf('%.2f',@store.rating) %> (95 notes)
        </div>
      </span>

      <span>
        Open till 11:00 PM
      </span>

      <div class="mt-2">
        Free delivery starting from 15 CHF
      </div>

      <div class="d-flex justify-content-between">
        <div>
          <%= image_tag("drone1.jpg", width: "28", height: "28", class:"rounded-circle") %>
          <span>Delivery in <%= @store.estimated_delivery_time%></span>
        </div>
      </div>
    </div>
  </div>


<!-- systeme de breakpoint -->

  <% categorys = Article.distinct.pluck(:category) %>

  <% categorys_underscore = categorys.map do |element| %>
    <% element.gsub(" ","_") %>
  <% end %>

  <div class="mt-5 py-1">
    <div class= "d-flex scroll text-nowrap">

      <a href="#store" class="category p-3 border text-dark text-decoration-none border">
        All
      </a>

      <a href="#<%=categorys_underscore[0]%>" class="category p-3 border text-dark text-decoration-none border">
        <%=categorys[0]%>
      </a>

      <a href="#<%=categorys_underscore[1]%>" class="category p-3 border text-dark text-decoration-none border">
        <%=categorys[1]%>
        </a>

      <a href="#<%=categorys_underscore[2]%>" class="category p-3 border text-dark text-decoration-none border">
        <%=categorys[2]%>
      </a>

      <a href="#<%=categorys_underscore[3]%>" class="category p-3 border text-dark text-decoration-none border">
        <%=categorys[3]%>
      </a>

      <a href="#<%=categorys_underscore[4]%>" class="category p-3 border text-dark text-decoration-none border">
        <%=categorys[4]%>
      </a>
    </div>
  </div>


  <!-- (faire l'itération pour la 1er catégorie Cooling) -->
  <h4 class="mb-4 mt-4 fs-1 title_category main" id="<%=categorys[0]%> category"><strong> <%=categorys[0]%> </strong></h4>

  <% @articles.each do |article| %>
    <%= link_to article_path(article), style: "text-decoration: none" do %>
      <% if article.category == categorys[0]%>
        <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
          <h3 class="fs-4 title text-dark"><%= article.title %></h3>
          <div class="main pb-2"><%= sprintf('%.2f', article.price.to_f) %> CHF</div>
          <span class="text-secondary"><%= article.description.truncate(24)%></span>
        </div>
        <div >
          <%= image_tag(article.image_url, width: "120", height: "120" ) %>
        </div>
      </div>
      <% else %>
      <% end %>
    <% end %>
  <%end%>

  <!-- (faire l'itération pour la 2eme catégorie skin & hair) -->
  <h4 class="mb-4 mt-4 fs-1 title_category main" id="<%=categorys_underscore[1]%>"><strong> <%=categorys[1]%> </strong></h4>

  <% @articles.each do |article| %>
    <%= link_to article_path(article), style: "text-decoration: none" do %>
      <% if article.category == categorys[1]%>
        <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
          <h3 class="fs-4 title text-dark"><%= article.title %></h3>
          <div class="main pb-2"><%= sprintf('%.2f', article.price.to_f) %> CHF</div>
          <span class="text-secondary"><%= article.description.truncate(24)%></span>
        </div>
        <div >
          <%= image_tag(article.image_url, width: "120", height: "120" ) %>
        </div>
      </div>
      <% else %>
      <% end %>
    <% end %>
  <%end%>

  <!-- (faire l'itération pour la 3eme catégorie) -->
  <h4 class="mb-4 mt-4 fs-1 title_category main" id="<%=categorys_underscore[2]%>"><strong> <%=categorys[2]%> </strong></h4>

    <% @articles.each do |article| %>
    <%= link_to article_path(article), style: "text-decoration: none" do %>
      <% if article.category == categorys[2]%>
        <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
          <h3 class="fs-4 title text-dark"><%= article.title %></h3>
          <div class="main pb-2"><%= sprintf('%.2f', article.price.to_f) %> CHF</div>
          <span class="text-secondary"><%= article.description.truncate(24)%></span>
        </div>
        <div >
          <%= image_tag(article.image_url, width: "120", height: "120" ) %>
        </div>
      </div>
      <% else %>
      <% end %>
    <% end %>
  <%end%>

  <!-- (faire l'itération pour la 4eme catégorie) -->
  <h4 class="mb-4 mt-4 fs-1 title_category main" id="<%=categorys_underscore[3]%>"><strong> <%=categorys[3]%> </strong></h4>

    <% @articles.each do |article| %>
    <%= link_to article_path(article), style: "text-decoration: none" do %>
      <% if article.category == categorys[3]%>
        <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
          <h3 class="fs-4 title text-dark"><%= article.title %></h3>
          <div class="main pb-2"><%= sprintf('%.2f', article.price.to_f) %> CHF</div>
          <span class="text-secondary"><%= article.description.truncate(24)%></span>
        </div>
        <div >
          <%= image_tag(article.image_url, width: "120", height: "120" ) %>
        </div>
      </div>
      <% else %>
      <% end %>
    <% end %>
  <%end%>

  <!-- (faire l'itération pour la 5eme catégorie) -->
  <h4 class="mb-4 mt-4 fs-1 title_category main" id="<%=categorys_underscore[4]%>"><strong> <%=categorys[4]%> </strong></h4>

    <% @articles.each do |article| %>
    <%= link_to article_path(article), style: "text-decoration: none" do %>
      <% if article.category == categorys[4]%>
        <div class="d-flex justify-content-between align-items-start mb-4">
        <div>
          <h3 class="fs-4 title text-dark"><%= article.title %></h3>
          <div class="main pb-2"><%= sprintf('%.2f', article.price.to_f) %> CHF</div>
          <span class="text-secondary"><%= article.description.truncate(24)%></span>
        </div>
        <div >
          <%= image_tag(article.image_url, width: "120", height: "120" ) %>
        </div>
      </div>
      <% else %>
      <% end %>
    <% end %>
  <%end%>
</div>